[package]
name = "treetraversal"
version = "0.0.1"
authors = ["Caleb Hattingh <caleb.hattingh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "itertree"

[dependencies]

[dev-dependencies]
rstest = "0.9.0"
